# Model weights
action_weight: 1.0
reconst_weight: 10.0
cot_weight: 1.0
separator_weight: 1.0
rollout_stop_weight: 1.0
wm_weight: 1.0

# Training configuration
action_sample_mode: 'future'  # 'random', 'future'
safe_reflect_rate: 0.3
collide_reflect_rate: 0.8
collide_rewind_rate: 0.8
max_rewind_step: 1
shortest_seq_rate: 0.0

# Model settings
use_wm: false
exp_name: 'debug'
llm_model: 'HuggingFaceTB/SmolLM2-135M-Instruct'  # 'gpt2', 'HuggingFaceTB/SmolLM2-135M-Instruct'
overfit: false
mask_collision_action: false
ckpt_path: null

# Training hyperparameters
batch_size: 18
num_epochs: 30
T_step: 711960
single_gpu: false

# Optimizer and scheduler settings
optimizer: 'adamw'  # 'adamw', 'adamw_default', 'adam'
lr: 1e-3
lr_scheduler: 'cosine'  # 'cosine', 'constant'
warmup_steps: 0
gradient_accumulation_steps: 1
loss_clip: 1.0

# Training control
fp16: false
torch_compile: false
rollout_only: false

# Logging and checkpointing
save_steps: 1000
log_freq: 50
rollout_steps: 5000
num_workers: 4
max_token_num: 512

# Data paths
data_folder: '/storage/Datasets/highway_env/highway_fast_v0_dqn_meta_action_5_lanes/rollouts_train_collision'
rollout_data_path: '/storage/Datasets/highway_env/highway_fast_v0_dqn_meta_action_5_lanes/rollouts_env/rollouts_env_states_1k.pkl'
save_root: '~/results/vla/quick_run_cot_unified_collision'

# Wandb configuration
wandb:
  project: 'vla_training'